local:
  build: .
  command: npm run dev
  ports:
    - 3000
  volumes:
    - .:/usr/src/app
  environment:
    VIRTUAL_HOST: universal.local.dockito.org
    VIRTUAL_PORT: 3000
    NODE_PATH: /usr/src/app/src
    NODE_ENV: development
    UV_THREADPOOL_SIZE: 100


production:
  build: .
  command: npm run start
  ports:
    - 3000
  volumes:
    - .:/usr/src/app
  environment:
    VIRTUAL_HOST: universal.local.dockito.org
    VIRTUAL_PORT: 3000
    NODE_PATH: /usr/src/app/src
    NODE_ENV: production
